# Generated by Django 5.1.2 on 2025-10-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_question_section_testgroup_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testgroup',
            name='passing_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
