# Generated by Django 5.1.2 on 2025-10-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_testgroup_passing_marks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testsection',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='question',
            name='passage_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('math_free', 'Math Free Answer')], default='mcq', max_length=20),
        ),
        migrations.AddField(
            model_name='testsection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testsection',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testsection',
            name='time_limit',
            field=models.IntegerField(blank=True, help_text='Time limit in minutes', null=True),
        ),
    ]
